config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root to: "pages#home"
  get 'damien_dashboard', to: "pages#dashboard"
  resources :messages, only: [ :create, :destroy ] do
    post '/check', to: 'messages#check!'
    post '/uncheck', to: 'messages#uncheck!'
  end
  resources :photos, only: [ :create, :destroy ]
  resources :videos, only: [ :create, :destroy ]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/message.rb
class Message < ApplicationRecord
  after_create :send_contact

  validates :name, presence: true
  validates :email, presence: true
  validates_format_of :email, :with => /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/i
  validates :content, length: { minimum: 20, maximum: 500 }


  private

  def send_contact
    MessageMailer.contact(self).deliver_now
  end
end

app/models/photo.rb
class Photo < ApplicationRecord
  mount_uploader :url, PhotoUploader
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable,
  # :registerable
  devise :database_authenticatable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/video.rb
class Video < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  before_action :authenticate_user!
  include Pundit

  after_action :verify_authorized, except: :index, unless: :skip_pundit?
  after_action :verify_policy_scoped, only: :index, unless: :skip_pundit?

  private

  def skip_pundit?
    devise_controller? || params[:controller] =~ /(^(rails_)?admin)|(^pages$)/
  end

  def default_url_options
    { host: ENV["HOST"] || "damienguillot.com" }
  end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  before_action :find_message, only: [ :destroy ]

  def create
    @message = Message.new(message_params)

    respond_to do |format|
      if @message.save
        format.js
      else
        format.html { render "/" }
        format.js
      end
    end
  end

  def destroy
  end

  def check!
    @message = Message.find(params[:message_id])
    @message.checked = true

    respond_to do |format|
      if @message.save
        format.js
      else
        format.html { render damien_dashboard_path }
        format.js
      end
    end
  end

  def uncheck!
    @message = Message.find(params[:message_id])
    @message.checked = false

    respond_to do |format|
      if @message.save
        format.js
      else
        # format.html { render damien_dashboard_path }
        format.js
      end
    end
  end

  private

  def find_message
    @message = Message.find(params[:id])
  end

  def message_params
    params.require(:message).permit(:name, :email, :phone, :content)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: :home
  before_action :message

  def home
    @photos = Photo.all
    @videos = Video.all
  end

  def dashboard
    @messages = Message.order("created_at DESC").all
    @photo = Photo.new
    @video = Video.new
  end

  private

  def message
    @message = Message.new
  end
end

app/controllers/photos_controller.rb
class PhotosController < ApplicationController
  before_action :find_photo, only: :destroy

  def create
    @photo = Photo.new(params_photo)
    authorize @photo

    if @photo.save
      redirect_to root_path
    else
      render damien_dashboard_path
    end
  end

  def destroy
    authorize @photo
    @photo.destroy
    redirect_to root_path
  end

  private

  def find_photo
    @photo = Photo.find(params[:id])
  end

  def params_photo
    params.require(:photo).permit(:caterogy, :url)
  end
end

app/controllers/videos_controller.rb
class VideosController < ApplicationController
  before_action :find_video, only: :destroy

  def create
    @video = Video.new(params_video)
    authorize @video

    if @video.save
      redirect_to root_path
    else
      render damien_dashboard_path
    end
  end

  def destroy
    authorize @video
    @video.destroy

    redirect_to root_path
  end

  private

  def find_video
    @video = Video.find(params[:id])
  end

  def params_video
    params.require(:video).permit(:url)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/message_helper.rb
module MessageHelper
end

app/helpers/meta_tags_helper.rb
module MetaTagsHelper
  def meta_title
    content_for?(:meta_title) ? content_for(:meta_title) : DEFAULT_META["meta_title"]
  end

  def meta_description
    content_for?(:meta_description) ? content_for(:meta_description) : DEFAULT_META["meta_description"]
  end

  def meta_image
    meta_image = (content_for?(:meta_image) ? content_for(:meta_image) : DEFAULT_META["meta_image"])
    # little twist to make it work equally with an asset or a url
    meta_image.starts_with?("http") ? meta_image : image_url(meta_image)
  end
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/photos_helper.rb
module PhotosHelper
end

app/helpers/videos_helper.rb
module VideosHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <%= favicon_link_tag(source='favicon-camera.ico', options={}) %>
    <title><%= meta_title %></title>
    <meta name="description" content="<%= meta_description %>">

    <!-- Facebook Open Graph data -->
    <meta property="og:title" content="<%= meta_title %>" />
    <meta property="og:type" content="website" />
    <meta property="og:url" content="<%= request.original_url %>" />
    <meta property="og:image" content="<%= meta_image %>" />
    <meta property="og:description" content="<%= meta_description %>" />
    <meta property="og:site_name" content="<%= meta_title %>" />
    <%= csrf_meta_tags %>
    
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.0.12/css/all.css" integrity="sha384-G0fIWCsCzJIMAVNQPfjH08cyYaUtMwjJwqiRKxxE/rx96Uroj1BtIQ6MLJuheaO9" crossorigin="anonymous">

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://cdn.plyr.io/3.3.10/plyr.css">
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
    <%= javascript_pack_tag  'application'%>
    <script src="https://cdn.plyr.io/3.3.10/plyr.js"></script>
    <script>const player = new Plyr('.player');</script>
  </body>

</html>

app/views/messages/_form.html.erb
<%= simple_form_for @message, remote: true  do |f| %>
  <%= f.input :name %>
  <span class="error" id="name-errro"></span>
  <%= f.input :email %>
  <span class="error" id="email-errro"></span>
  <%= f.input :phone %>
  <span class="error" id="phone-errro"></span>
  <%= f.input :content %>
  <span class="error" id="content-errro"></span>
  <%= f.button :submit, value: 'Send', class: "btn-form" %>
<% end %>

app/views/messages/check!.js.erb
var nbUncheckedMessages = document.getElementById('nb-unchecked-messages');

nbUncheckedMessages.innerText = '<%= Message.where(checked: false).count %>';

var messageBoxes = document.querySelectorAll('.message');

<% Message.all.each do |message| %>
  <% if message.checked %>
    messageBoxes.forEach(function(messageBox) {
      if ( messageBox.dataset.messageId === '<%= message.id %>') {
        messageBox.style.backgroundColor = '#F4F4F4';
        var actionDiv = messageBox.querySelector('.message-state-action');
        actionDiv.innerHTML =
        '<%= link_to 'Mark as unchecked', message_uncheck_path(message), remote: true, method: :post %>';
      }
    });
  <% end %>
<% end %>

app/views/messages/create.js.erb
<% if @message.valid? %>
  const formContainer = document.querySelector('.form-container')
  formContainer.innerHTML = `
  <div class="thanks-message-container">
    <h3 id="thanks-message">Thanks for your message!</h3>
  </div>`;


  // var messageContainer = document.querySelector('.container-messages');
  // alert(messageContainer);


  // messageContainer.innerHTML = `
  //   <div class="message" style="background-color: #ccc" data-message-id="<%= @message.id %>">
  //     <div class="message-display-part">
  //       <span><%= @message.created_at.strftime("%^b %d %Y at %I:%M%p") %></span>
  //       <span><%= @message.name %></span>
  //       <span><%= @message.email %></span>
  //       <div class="message-state-action" data-message-id="<%= @message.id %>">
  //         <% if @message.checked %>
  //         <%= link_to 'Mark as unchecked', message_uncheck_path(@message), remote: true, method: :post %>
  //         <% else %>
  //         <%= link_to 'Mark as checked', message_check_path(@message), remote: true, method: :post %>
  //         <% end %>
  //       </div>
  //     </div>
  //     <div class="message-hidden-part">
  //       <span><%= @message.content %></span>
  //       <span><%= @message.phone ? @message.phone : "" %></span>
  //     </div>
  //   </div>
  // `;
<% else %>

  function erros(field, messageError) {
    document.getElementById(`${field}-errro`).innerText = messageError;
    document.querySelector(`.message_${field} label`).style.color = '#8d7ed0';
    document.getElementById(`message_${field}`).style.borderColor = '#8d7ed0';
  }

  function noErros(field) {
    document.getElementById(`${field}-errro`).innerText = '';
    document.querySelector(`.message_${field} label`).style.color = '#000000';
    document.getElementById(`message_${field}`).style.borderColor = '#ccc';
  }

  <% if @message.errors[:name][0].nil? %>
    noErros('name');
  <% else %>
    erros('name', '<%= @message.errors[:name][0] %>');
  <% end %>

  <% if @message.errors[:email][0].nil? %>
    noErros('email');
  <% else %>
    erros('email', '<%= @message.errors[:email][0] %>');
  <% end %>

  <% if @message.errors[:phone][0].nil? %>
    noErros('phone');
  <% else %>
    erros('phone', '<%= @message.errors[:phone][0] %>');
  <% end %>

  <% if @message.errors[:content][0].nil? %>
    noErros('content');
  <% else %>
    erros('content', '<%= @message.errors[:content][0] %>');
  <% end %>

<% end %>

app/views/messages/uncheck!.js.erb
var sup = document.getElementById('sup');
console.log(sup);

var nbUncheckedMessages = document.getElementById('nb-unchecked-messages');

nbUncheckedMessages.innerText = '<%= Message.where(checked: false).count %>';

var messageBoxes = document.querySelectorAll('.message');
var messagesStateAction = document.querySelectorAll('.message-state-action');

<% Message.all.each do |message| %>
  <% if !message.checked %>
    messageBoxes.forEach(function(messageBox) {
      if ( messageBox.dataset.messageId === '<%= message.id %>') {
        messageBox.style.backgroundColor = '#ccc';
        var actionDiv = messageBox.querySelector('.message-state-action');
        actionDiv.innerHTML =
        '<%= link_to 'Mark as checked', message_check_path(message), remote: true, method: :post %>';
      }
    });
  <% end %>
<% end %>

app/views/pages/dashboard.html.erb
<h1 class="text-center">Dashboard</h1>

<div class="container container-messages">
  <p>You have <strong><%= Message.count %></strong> messages in your inbox, and you still have <span id="nb-unchecked-messages" style="text-decoration: underline;"><%= Message.where(checked: false).count %></span> unread messages</p>
  <% @messages.each do |message| %>
    <% if message.checked %>
      <div class="message" data-message-id="<%= message.id %>">
    <% else %>
      <div class="message" style="background-color: #ccc" data-message-id="<%= message.id %>">
    <% end %>
      <div class="message-display-part">
        <span><%= message.created_at.strftime("%^b %d %Y at %I:%M%p") %></span>
        <span><%= message.name %></span>
        <span><%= message.email %></span>
      <div class="message-state-action" data-message-id="<%= message.id %>">
        <% if message.checked %>
          <%= link_to 'Mark as unchecked', message_uncheck_path(message), remote: true, method: :post %>
        <% else %>
          <%= link_to 'Mark as checked', message_check_path(message), remote: true, method: :post %>
        <% end %>
      </div>
      </div>
      <div class="message-hidden-part">
        <span><%= message.content %></span>
        <span><%= message.phone ? message.phone : "" %></span>
      </div>
    </div>
  <% end %>
</div>

<div class="container container-photos">
  <h3>Add a photo</h3>
  <%= simple_form_for @photo do |f| %>
    <%= f.input :category, collection: [ 'event', 'profile', 'food', 'portrait', 'corporate' ] %>
    <%= f.file_field :url %>
    <%= f.input :url_cache, as: :hidden %>
    <%= f.button :submit %>
  <% end %>
</div>

<div class="container container-videos">
  <h3>Add a video</h3>
  <%= simple_form_for @video do |f| %>
    <%= f.input :url %>
    <%= f.button :submit %>
  <% end %>
</div>

app/views/pages/home.html.erb
<div class="screen">
  <%= render 'shared/navigation' %>
  <div class="content-wrapper">
    <%= render 'shared/landing' %>
    <%= render 'shared/photos' %>
    <%= render 'shared/videos' %>
    <%= render 'shared/instagram' %>
    <%= render 'shared/contact' %>
  </div>
</div>

app/views/shared/_contact.html.erb
<div class="section-slidinhojs contact-section">

    <%= cl_image_tag 'PictureNearForm-compressor.jpg', class: 'image-contact-section' %>
  <div class="form-wrapper">
    <div class="body">
      <h2>CREATOR.</h2>
      <p>Located in Montreal</p>
    </div>
    <div class="form">
      <h2>LETS CONNECT.</h2>
      <%= render 'messages/form' %>
    </div>
  </div>
</div>

app/views/shared/_instagram.html.erb
<div class="section-slidinhojs instagram-section">
  <div class="container-instagram">
    <div class="row">

    </div>
  </div>
</div>

app/views/shared/_landing.html.erb
<div class="section-slidinhojs landing-section section-active">
  <div class="landing-image" style="background-image: url('<%= cl_image_path "Leonard-Cohen-compressor.jpg" %>')">
    <a href="https://www.instagram.com/damien_guillot_/" id="instagram-small-screen" class="instagram" target="_blank">
      <i class="fab fa-instagram"></i>
    </a>
  </div>
</div>

app/views/shared/_logo.html.erb
<div id="nav-landing" class="container-logo">
 <!--  <svg viewBox="0 0 78 78" width="40" height="40" style="enable-background:new 0 0 78 78;">
  <defs>
    <linearGradient id="linear" x1="0%" y1="0%" x2="100%" y2="0%">
      <stop offset="0%"   stop-color="#5fa7e6"/>
      <stop offset="50%"  stop-color="#e51faa"/>
    </linearGradient>
  </defs>
    <path class="st0" d="M72,12.5H55l-6.1-7c-0.6-0.7-1.4-1-2.3-1H31.4c-0.9,0-1.7,0.4-2.3,1l-6.1,7H6c-3.3,0-6,2.7-6,6v40
    c0,3.3,2.7,6,6,6h13.6c4.7,5.5,11.6,9,19.4,9s14.8-3.5,19.4-9H72c3.3,0,6-2.7,6-6v-40C78,15.2,75.3,12.5,72,12.5z M39,67.5
    c-10.8,0-19.5-8.7-19.5-19.5c0-10.8,8.7-19.5,19.5-19.5S58.5,37.2,58.5,48C58.5,58.8,49.8,67.5,39,67.5z M72,57.5c0,0.6-0.4,1-1,1
    h-8.8c1.4-3.2,2.3-6.8,2.3-10.5c0-14.1-11.4-25.5-25.5-25.5c-14.1,0-25.5,11.4-25.5,25.5c0,3.7,0.8,7.3,2.3,10.5H7c-0.6,0-1-0.4-1-1
    v-38c0-0.6,0.4-1,1-1h18.7l1.8-2l5.2-6h12.5l5.2,6l1.8,2H71c0.6,0,1,0.4,1,1V57.5z M39,32c-9.1,0-16.5,7.4-16.5,16.5
    c0,1.7,1.3,3,3,3c1.7,0,3-1.3,3-3C28.5,42.7,33.2,38,39,38c1.7,0,3-1.3,3-3C42,33.3,40.7,32,39,32z M9.9,28.5h6v-6h-6V28.5z" transform="matrix(1, 0, 0, 1, 0, -8.881784197001252e-16)" x="10" y="10" width="600" height="200" fill="url(#linear)" ></path>
  </svg> -->
  <h1 class="logo-title"> DAMIEN GUILLOT </h1>
</div>

app/views/shared/_navigation.html.erb
<div class="navigation">
  <div class="nav-wrapper">
    <%= render 'shared/logo' %>
    <div class="left-nav">
      <ul>
        <li id="nav-photos">PHOTOS</li>
        <li id="nav-videos">VIDEOS</li>
        <li id="nav-contact">ABOUT</li>
      </ul>
      <div class="footer">
        <a href="https://www.instagram.com/damien_guillot_/" id="instagram-full-screen" class="instagram" target="_blank">
          <i class="fab fa-instagram"></i>
        </a>
        <p class="copyright">© Damien Guillot</p>
      </div>
    </div>
  </div>
</div>

app/views/shared/_photos.html.erb
<div class="section-slidinhojs photos-section">
  <div id="container-photos">
    <% i = 0 %>
    <div class="row">
      <% @photos.each do |photo| %>
        <% i += 1 %>
        <div class="col-xs-12 col-sm-6 col-md-4">
          <%= cl_image_tag photo.url, :data => { :index => i } %>
          <% if policy(Photo).destroy? %>
            <%= link_to photo_path(photo), :method => :delete, :data => { :confirm => "Are you really sure?"} do %>
              <i class="far fa-trash-alt delete-photo"></i>
            <% end %>
          <% end %>
        </div>
      <% end %>
    </div>
  </div>

  <div id="slider-container">
    <div id="closing-cross">
      <div id="cross-vertical-part"></div>
      <div id="cross-horizontal-part"></div>
    </div>
    <div id="arrow-left"></div>
    <% j = 0 %>
    <% @photos.each do |photo| %>
      <% j += 1 %>
      <%= cl_image_tag photo.url, class: 'photo-slider', :data => { :index => j } %>
    <% end %>
    <div id="arrow-right"></div>
  </div>

</div>

app/views/shared/_videos.html.erb
<div class="section-slidinhojs videos-section">
  <div class="container-videos">
    <div class="row">
      <% @videos.each do |video| %>
        <div class="col-xs-12 column-video">
          <% if policy(Video).destroy? %>
            <%= link_to video_path(video), :method => :delete, :data => {:confirm => "Are you really sure?"} do %>
              <i class="far fa-trash-alt delete-photo"></i>
            <% end %>
            <iframe src="<%= video.url %>" width="640" height="450" frameborder="0" webkitallowfullscreen mozallowfullscreen allowfullscreen></iframe>
          <% else %>
            <iframe src="<%= video.url %>" width="640" height="450" frameborder="0" webkitallowfullscreen mozallowfullscreen allowfullscreen></iframe>
          <% end %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/videos/create.html.erb
<h1>Videos#create</h1>
<p>Find me in app/views/videos/create.html.erb</p>

app/views/videos/destroy.html.erb
<h1>Videos#destroy</h1>
<p>Find me in app/views/videos/destroy.html.erb</p>